### ISSUE TITLE
Error while loading shared libraries: libQuasarApp.so.1

### ISSUE THREAD

**Issue by greenpeas** [QuasarApp/Console-QtDeployer#179]
anton@debian:~/QTProjects/Release$ ~/CQtDeployer/bin/cqtdeployer -bin TurniketPhotoViewer -qmake ~/Qt/5.13.1/gcc_64/bin/qmake 
/home/anton/CQtDeployer/bin/cqtdeployer: error while loading shared libraries: libQuasarApp.so.1: cannot open shared object file: No such file or directory

**Comment by EndrII** [comment]
Hello, your problem exists because you run it without setting up the environment. CQtDeployer environment is set up already. Run it with the help of **cqtdeployer** command. If you installed the program with the the help of installer, you should restart your computer.

For Example :
```
cqtdeployer -bin TurniketPhotoViewer -qmake ~/Qt/5.13.1/gcc_64/bin/qmake
```

**Comment by EndrII** [comment]
did you manage to solve the problem?

**Comment by EndrII** [comment]
apparently the problem is solved

**Comment by greenpeas** [comment]
Rebooting the computer solved the problem. Thank you.

**Comment by Megidd** [comment]
In my case the error got resolved by replacing this bad call:

```
~/CQtDeployer/1.5/bin/cqtdeployer -bin appname -qmake ~/Qt5.12.11/5.12.11/gcc_64/bin/qmake -qmldir ~/repos/apprepo//editorlib/qml/
```

With this good one:

```
~/CQtDeployer/1.5/cqtdeployer.sh -bin appname -qmake ~/Qt5.12.11/5.12.11/gcc_64/bin/qmake -qmldir ~/repos/apprepo//editorlib/qml/
```
Basically, replacing `~/CQtDeployer/1.5/bin/cqtdeployer` with `~/CQtDeployer/1.5/cqtdeployer.sh` :smiley:
